[package]
name = "gameplay"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
bevy.workspace = true
bevy_enhanced_input.workspace = true
bevy_rand.workspace = true
rand_core.workspace = true
game_assets.workspace = true
game_audio.workspace = true
game_settings.workspace = true

[dev-dependencies]
bevy_asset_loader.workspace = true
