[package]
name = "game_core"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[features]
debug = ["dep:debug"]
steam = ["game_achievements/steam"]

[dependencies]
bevy.workspace = true
capture.workspace = true
bevy_enhanced_input.workspace = true
game_achievements.workspace = true
game_assets.workspace = true
game_audio.workspace = true
bevy_rand.workspace = true
rand_core.workspace = true
gameplay.workspace = true
game_ui.workspace = true
game_settings.workspace = true
transport.workspace = true
debug = { workspace = true, optional = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2"
web-sys = { version = "0.3", features = ["Document", "Element", "EventTarget", "Window"] }

[dev-dependencies]
bevy_asset_loader.workspace = true
serde_json = "1"
