[package]
name = "game_core"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[features]
debug = ["dep:debug"]

[dependencies]
bevy.workspace = true
capture.workspace = true
bevy_enhanced_input.workspace = true
game_assets.workspace = true
game_audio.workspace = true
bevy_rand.workspace = true
rand_core.workspace = true
gameplay.workspace = true
game_ui.workspace = true
game_settings.workspace = true
transport.workspace = true
debug = { workspace = true, optional = true }

[dev-dependencies]
bevy_asset_loader.workspace = true
serde_json = "1"
