[package]
name = "game_core"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[features]
debug = ["dep:debug"]

[dependencies]
bevy.workspace = true
bevy_enhanced_input.workspace = true
game_assets.workspace = true
gameplay.workspace = true
transport.workspace = true
debug = { workspace = true, optional = true }

[dev-dependencies]
serde_json = "1"
